title: "Flow Recipes [WIP]"
description: "Information about the FlowRecipes repository, part of SFDO Community Sprints"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"

# Aux links for the upper right navigation
aux_links:
  "FlowRecipes on GitHub":
    - "//github.com/SFDO-Community-Sprints/FlowRecipes"
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true

#Footer
footer_content: "Flow Recipes is a repository built and maintained by a community of volunteers through the Open Source Commons program. This is not a Salesforce-owned product. If you need support, raise an issue in the github repo :) "

# Search Settings
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
########################################################

# Replaces title if used
# logo: "/assets/images/dlrs-badge.png"

# "favicon.ico" used to change default favicon